spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# CricAPI - get free key from https://api.cricapi.com/
cricapi.key=
